# Generated by Django 5.0.14 on 2026-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_options_user_unique_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('rider', 'Rider'), ('admin', 'Admin'), ('staff', 'Staff'), ('washer', 'Washer'), ('folder', 'Folder'), ('fumigator', 'Fumigator')], default='customer', max_length=20),
        ),
    ]
