# Generated by Django 5.0.14 on 2026-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offernotificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='benefit_type',
            field=models.CharField(choices=[('cash_discount', 'Cash Discount'), ('free_delivery', 'Free Delivery'), ('other', 'Other')], default='cash_discount', max_length=30),
        ),
    ]
