# Generated by Django 5.0.14 on 2026-09-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('requested', 'Order Requested'), ('pending_assignment', 'Pending Pickup Assignment'), ('assigned_pickup', 'Assigned for Pickup'), ('picked', 'Picked Up'), ('in_progress', 'In Progress'), ('washed', 'Washed'), ('folded', 'Folded'), ('ready', 'Ready for Delivery'), ('pending_delivery', 'Pending Delivery Assignment'), ('assigned_delivery', 'Assigned for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
