# Generated by Django 5.0.14 on 2026-09-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_benefit_type'),
        ('orders', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_offer',
            field=models.ForeignKey(blank=True, help_text='Offer claimed and applied during checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_with_offer', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='Whether delivery is free for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash discount deducted from the order price', max_digits=10),
        ),
    ]
